server:
  port: 9999
  servlet:
    context-path: /warehouse

spring:
  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/db_warehouse?serverTimezone=Asia/Shanghai&userUnicode=true&&characterEncoding=UTF-8
#    username: root
#    password: 123456
#    driver-class-name: com.mysql.cj.jdbc.Driver
    dynamic:
      primary: master
      strict: false
      datasource:
        master:
          url: jdbc:mysql://192.168.65.131:3306/db_warehouse?serverTimezone=Asia/Shanghai&userUnicode=true&&characterEncoding=UTF-8
          username: root
          password: abc123
          driver-class-name: com.mysql.cj.jdbc.Driver
        slave:
          url: jdbc:mysql://192.168.65.132:3306/db_warehouse?serverTimezone=Asia/Shanghai&userUnicode=true&&characterEncoding=UTF-8
          username: root
          password: abc123
          driver-class-name: com.mysql.cj.jdbc.Driver

#          master:
#            url: jdbc:mysql://127.0.0.1:3306/db_warehouse?serverTimezone=Asia/Shanghai&userUnicode=true&&characterEncoding=UTF-8
#            username: root
#            password: 123456
#            driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password:

warehouse:
  expire-time: 28800

file:
  upload-path: /static/img/upload
  access-path: /img/upload/

#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  configuration:
#    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


mybatis-plus:
  type-aliases-package: com.q1linz.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

